### Listar moedas
GET http://localhost:3333/moedas

###

### Criar moeda
POST http://localhost:3333/moedas
Content-Type: application/json

{
    "name": "Insane Clown",
    "descricao": "Pra treinar potente!"
}

###

### Atualizar moeda
PUT http://localhost:3333/moedas/70bd845b-03ed-44ef-ab71-70af255e7258
Content-Type: application/json

{
    "naasdme": "Palhaço Insano",
    "descricao": "Pré treino mais forte do mercado."
}

###

### Deletar moeda
DELETE http://localhost:3333/moedas/id
